version: '3.8'

services:
  floxy-pro-pg:
    container_name: floxy-pro-pg
    image: rom8726/postgres-partman:latest
    restart: always
    environment:
      POSTGRES_USER: floxy
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: floxy
      PGDATA: /var/lib/postgresql/data/pgdata
    command: -c config_file=/etc/postgresql.conf
    volumes:
      - "floxy_pro_pg:/var/lib/postgresql/data/pgdata"
      - "./postgres_initdb:/docker-entrypoint-initdb.d"
      - "./postgresql.conf:/etc/postgresql.conf"
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U floxy -d floxy || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  floxy-pro-migrate:
    container_name: floxy-pro-migrate
    image: migrate/migrate:v4.17.0
    depends_on:
      floxy-pro-pg:
        condition: service_healthy
    environment:
      POSTGRES_USER: floxy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: floxy
    volumes:
      - "../migrations_pro:/migrations_pro"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "PostgreSQL is healthy — running migrations...";
        migrate -path /migrations_pro -database "postgres://$$POSTGRES_USER:$$POSTGRES_PASSWORD@floxy-pro-pg:5432/$$POSTGRES_DB?sslmode=disable&search_path=workflows" up;
        echo "✅ Migrations applied successfully!";
    restart: "no"

  floxy-manager:
    image: rom8726/floxy-manager:latest
    container_name: floxy-manager
    restart: always
    environment:
      API_SERVER_ADDR: ":3001"
      FRONTEND_URL: "http://localhost:3001"
      JWT_SECRET_KEY: "secret_123456789"
      MAILER_ADDR: "smtp.example.com:465"
      MAILER_FROM: "noreply@floxy.local"
      MAILER_PASSWORD: "password"
      MAILER_USER: "user"
      POSTGRES_DATABASE: "floxy"
      POSTGRES_HOST: "floxy-pro-pg"
      POSTGRES_PASSWORD: "password"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "floxy"
      SECRET_KEY: "secret_123456789"
      TECH_SERVER_ADDR: ":8081"
      ADMIN_EMAIL: "admin@floxy.local"
      ADMIN_TMP_PASSWORD: "Floxy123!"
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      floxy-pro-pg:
        condition: service_healthy
      floxy-pro-migrate:
        condition: service_completed_successfully
    command: ["/app/main", "server"]

  floxyd:
    image: rom8726/floxyd:latest
    container_name: floxyd
    restart: always
    environment:
      FLOXY_DB_NAME: "floxy"
      FLOXY_DB_HOST: "floxy-pro-pg"
      FLOXY_DB_PASSWORD: "password"
      FLOXY_DB_PORT: "5432"
      FLOXY_DB_USER: "floxy"
    volumes:
      - "./floxyd.yml:/app/config.yml"
    depends_on:
      - floxy-pro-pg
      - floxy-pro-migrate
    entrypoint: ["/app/floxyd", "/app/config.yml"]

volumes:
  floxy_pro_pg:
